name: Deploy Angular app with PNPM to GitHub Pages

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    permissions:
      contents: write
    if: ${{ github.repository_owner }} == 'shiv-source'
    uses: shiv-source/workflows/.github/workflows/angular-pnpm-gh-pages.yml@master
    with:
      ANGULAR_BUILD_DIR: ./dist/my-angular-app/
      ANGULAR_BUILD_COMMAND: pnpm build:prod
