name: PR build check

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Using PNPM cache version 8
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Installing project dependencies
        run: pnpm install
      - name: Building project
        run: pnpm build:prod
